[package]

name    = "inotify"
version = "0.7.1-dev"
authors = [
  "Hanno Braun <mail@hannobraun.de>",
  "Félix Saparelli <me@passcod.name>",
  "Cristian Kubis <cristian.kubis@tsunix.de>",
  "Frank Denis <github@pureftpd.org>"
]
edition = "2018"

description   = "Idiomatic wrapper for inotify"
documentation = "https://docs.rs/inotify"
repository    = "https://github.com/inotify-rs/inotify"
license       = "ISC"
readme        = "README.md"

keywords   = ["inotify", "linux"]
categories = ["api-bindings", "filesystem"]
exclude    = ["/.travis.yml", "/inotify-rs.sublime-project"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci   = { repository = "inotify-rs/inotify" }


[features]
default = ["stream-tokio"]
stream-tokio = ["futures-core", "mio", "tokio"]


[dependencies]
bitflags     = "1"
futures-core = { version = "0.3.1", optional = true }
inotify-sys  = "0.1.3"
libc         = "0.2"
mio          = { version = "0.6", optional = true }
tokio        = { version = "0.2.1", optional = true, features = ["io-driver"] }

[dev-dependencies]
tempdir      = "0.3"
futures-util = "0.3.1"
tokio        = { version = "0.2.1", features = ["macros", "rt-core"] }

[[example]]
name              = "stream-tokio"
required-features = ["stream-tokio"]

[[example]]
name = "watch"

[package.metadata.release]
pre-release-commit-message = "chore: Release version {{version}}"
pro-release-commit-message = "chore: Bump version to {{version}}"
tag-prefix                 = "v"
tag-message                = "Version {{version}}"
dev-version-ext            = "dev"
